---
version: '3'

services:
  drupal:
    image: jeffgeerling-com:latest
    build: .
    container_name: jeffgeerling-com
    environment:
      DRUPAL_DATABASE_HOST: 'mysql'
      DRUPAL_DATABASE_PORT: '3306'
      DRUPAL_DATABASE_NAME: 'drupal'
      DRUPAL_DATABASE_USERNAME: 'drupal'
      DRUPAL_DATABASE_PASSWORD: 'drupal'
      DRUPAL_DOWNLOAD_IF_NOT_PRESENT: 'false'
    ports:
      - "80:80"
    # restart: on-failure
    # Share the project into the container for local development. Comment out
    # this line to test the production-ready pre-built container codebase.
    volumes:
      - shared:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: drupal-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    # restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql

  bg-sync:
    image: cweagans/bg-sync
    volumes:
      - .:/source
      - shared:/var/www/html
    environment:
      - SYNC_DESTINATION=/var/www/html
      - SYNC_MAX_INOTIFY_WATCHES=50000
      - SYNC_VERBOSE=1
    privileged: true

volumes:
  shared:
