---
version: '3.8'

services:
  drupal:
    image: jeffgeerling-com:latest
    build: .
    container_name: jeffgeerling-drupal
    environment:
      DRUPAL_DATABASE_HOST: 'mysql'
      DRUPAL_DATABASE_PORT: '3306'
      DRUPAL_DATABASE_NAME: 'drupal'
      DRUPAL_DATABASE_USERNAME: 'drupal'
      DRUPAL_DATABASE_PASSWORD: 'drupal'
      DRUPAL_DOWNLOAD_IF_NOT_PRESENT: 'false'
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:rw,delegated
    # restart: on-failure

  mysql:
    image: mariadb:10
    container_name: jeffgeerling-mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    # restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql

  # For local development.
  mailhog:
    image: cd2team/mailhog:latest
    container_name: jeffgeerling-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
